### ISSUE TITLE
Centrally define dev image build action

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/.github#2]
Move build steps from the [build-dev-image template](https://github.com/PlaceOS/.github/blob/main/workflow-templates/build-dev-image.yml) (and by extension copies in each repo) into a composite run action, which service repos then reference. This should DRY up some of the config and help keep container formats, metadata and other cruft consistent.

This can then be reference as a single step in a general CI workflow.

**Comment by KimBurgess** [comment]
Action defined in [actions/build-dev-image.yml](https://github.com/PlaceOS/.github/blob/main/actions/build-dev-image/action.yml).

Blocked on usage until https://github.com/actions/runner/issues/646 is resolved.

**Comment by caspiano** [comment]
This will be a relatively simple task.

The only requirements are...

- extracting the build dev image workflow into the `.github` repo

- updating several of our services to call the centrally defined workflow

  + [ ] auth
  + [ ] build
  + [ ] core
  + [ ] dispatch
  + [ ] frontend-loader
  + [ ] init
  + [ ] nginx
  + [ ] portal-api
  + [ ] rest-api
  + [ ] rubber-soul
  + [ ] source
  + [ ] staff-api
  + [ ] triggers
