### ISSUE TITLE
Community health files

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/.github#4]
Provide a set of [community health files](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file).

This should include:
- [x] where external contributions are suitable
- [x] CoC
- [x] security contact
- [x] support information

**Comment by caspiano** [comment]
It would be good if we could validate across repos in the release that they have these files, and that they are in sync with this repository (also regarding automation as well)

**Comment by kimburgess** [comment]
No need. What's defined here [applies org wide unless overridden in repos](https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/).

**Comment by caspiano** [comment]
Oh nice!

Can we do the same with actions?

**Comment by kimburgess** [comment]
Unfortunately not. You can define templates for these ([like this](https://github.com/PlaceOS/.github/tree/main/workflow-templates)), but this only simplifies initial setup in repos using this. AFAIK there's no way to centrally define a composite action that you can maintain in one step. See https://github.com/PlaceOS/.github/issues/2.

**Comment by kimburgess** [comment]
One solution could be to define a single action that wraps a CI flow we want to standardise on (e.g. running linting, format checks, spec running and doc gen), then just use this everywhere.
