### ISSUE TITLE
Spec container builds are failing

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/.github#49]
**Describe the bug**

Spec containers as specified by `Dockerfile` are failing.

**To Reproduce**

Run `docker build .` in the repository root.

**Expected behavior**

Build to succeed.

**Additional context**

See [the build logs](https://github.com/PlaceOS/.github/actions/runs/1943328692)

**Comment by caspiano** [comment]
This should be fixed as soon as possible, because the `nightly` builds of crystal and weekly specs of our services help keep us on the edge of development safely

**Comment by chillfox** [comment]
There is an official kcov image now https://hub.docker.com/r/kcov/kcov

**Comment by chillfox** [comment]
The official image is based on Debian, but as we are copying all the dependencies across I think it should still work in an alpine image. If not then we can get the binary off the GitHub release page.

`flant/kcov-alpine` is pretty much unmaintained.
