### ISSUE TITLE
Build and host docs for each crystal project/library

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/.github#7]
Host the output of `crystal docs` for each repository for each tagged release.
This provides an easy way to view the surface of libraries and services that we build.

Ideally, each output should be hosted in a similar fashion to how crystal's API documentation is hosted.

`<github pages docs domain>/<repo>/<version>`

with a `version` of `latest` directing to the most recent tagged version.

**Comment by kimburgess** [comment]
Yes! This is something that I've been lusting for. We may be able to solve this a little more generally than a static set of builds. Given this output is _very_ deterministic it is possible to just build these lazily. This way you could hit `example.com/<owner>/<repo>/<version>` and get what you need.

First load will get hit the latency of the docs build. This could be solved by having a local GitHub Action in each repo run the initial request when a new tag appears so it's not a human experiencing that. We could (ab)use the GH infra further too to both host the output under GitHub pages _and_ run the doc builds themselves. This should just need something like a Cloudflare worker in front of it to trigger a workflow dispatch and return a HTTP 202, or redirect to previously built output.

We can place a filter on the owners / repo this will accept request for, but means others can reuse this too and change the settings for their needs.

**Comment by caspiano** [comment]
I think we should try to solve this for ourselves first in a relatively simple way, which the above is a good path towards.
I'd be hesitant to make such a valuable contribution to crystal tied so heavily to github's infrastructure.
A generic docs service would be _the best_, [docs.rs](https://docs.rs) being the gold standard in my opinion.

**Comment by caspiano** [comment]
This is out of the scope of PlaceOS's platform development.
This however would be an extremely useful thing to develop a basis for - like crates.io
